name: 03 - Schedule

on:
  schedule:
    - cron: '0 14 * * Mon'
    - cron: '0 14 * * fri'

jobs:
  schedule:
    runs-on: ubuntu-24.04
    steps:
      - name: Saludar
        run: echo "Hola desde GitHub Actions"